### PR TITLE
Switch back to JDK 1.7

### PR DESCRIPTION
**Pull request by oscerd**
We can go back to JDK 1.7 support, then we can switch back to JDK 1.7 on hawtio too.

Can you release the 0.9.11?

### CODE REVIEW

**Comment by oscerd** [comment]
We need to change the java version used on CI for this job to 1.7

**Comment by davsclaus** [comment]
retest this please

**Comment by jstrachan** [comment]
retest this please

**Comment by jstrachan** [comment]
@oscerd 0.9.11 is now out!

**Pull request merged**
