### PR TITLE
Jgit upgrade

### PR DESCRIPTION
**Pull request by oscerd**
- Upgrade Jgit to version 4.1.1.201511131810-r
- Removed project, settings etc. files

Tests are ok.

Now we need to manage the pom and change groupId

### CODE REVIEW

**Comment by jstrachan** [comment]
ok to test

**Comment by oscerd** [comment]
The build fails because we need to enter into org.gitective.core folder

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
@oscerd thx; yeah just spotted that ;) lets see if this build works....

**Pull request merged**
